version: '2'
services:
    official-website:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            args:
                version: R
        image: official-website
        restart: always
        ports:
            - 8400:80
