version: '2'
services:
    car-wash-admin:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            args:
                version: R
        image: car-wash-admin
        restart: always
        ports:
            - 8300:80
